eclipse-ee4j/glassfish-concurro

src/main/java/org/glassfish/enterprise/concurrent/ManagedThreadFactoryImpl.java
Currently when an exception is thrown in a managed thread all that is printed out is the name of the exception with no further details. This makes it so that if a managed thread throws an exception than the name of the thread and the full stack trace will be printed.
=> Exception in managed thread now prints full stack trace

CONTRIBUTING.md, NOTICE.md, README.md, pom.xml
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> Change project name to Jakarta Concurrency

pom.xml, src/main/java/org/glassfish/enterprise/concurrent/ManagedThreadFactoryImpl.java
Fixed version number back to -SNAPSHOT, so it can be built by Jenkins build.
Also added the change requested by @arjantijms in the last PR.
=> Fix version number

pom.xml, src/main/java/org/glassfish/enterprise/concurrent/AbstractManagedExecutorService.java, src/main/java/org/glassfish/enterprise/concurrent/AsynchronousInterceptor.java, src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedCompletableFuture.java
* Update versions in pom
* Set to JDK 11
* Add enforcer for defined Maven version
* Remove old staging/build profiles (now done in EE4J parent)
* Removed unused dependency
Updated javadoc that prevented building on JDK 11 and JDK 17.
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>
=> Updating and tidying pom

src/main/java/org/glassfish/enterprise/concurrent/internal/ContextProxyInvocationHandler.java
The previous implementation threw InvocationTargetException in contextual call. The new implementation throws the original exception, which makes it easier to understand the chain of causes of the exceptions.
In TCK, this passes the assert in ManagedScheduledExecutorDefinitionServlet.testCompletedFutureMSE: https://github.com/jakartaee/concurrency/blob/master/tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionServlet.java#L229
=> Remove invocation exception from exception causes

src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedScheduledThreadPoolExecutor.java
The inner future (currentFuture) is used for repeating execution and its state is set to NORMAL/[Completed normally] after each cycle. The TriggerControllerFuture.cancel should return true even if this inner future is done.
=> FISH-6556 Succeed TriggerControllerFuture.cancel When Inner Future is Done

osgi.bundle
forgotten OSGi version upgrade
I'm not sure if it is required (2.0 was there for the whole 3.0 version), but it seems to me that we should correct it.
=> Update OSGi Version

src/main/java/org/glassfish/enterprise/concurrent/AbstractManagedExecutorService.java, src/main/java/org/glassfish/enterprise/concurrent/ForkJoinManagedExecutorService.java, src/main/java/org/glassfish/enterprise/concurrent/ManagedExecutorServiceImpl.java, src/main/java/org/glassfish/enterprise/concurrent/ManagedScheduledExecutorServiceImpl.java
This is used by all MESes, so it makes sense to be be accessible at this level.
=> Publish getAdapter to AbstractManagedExecutorService

pom.xml
Without this, the new Java 21 classes are not visible to the compiler when the concurro JAR is used as a dependency.
=> Fixes multirelease JAR - adds a required manifest entry

src/main/java21/org/glassfish/enterprise/concurrent/virtualthreads/VirtualThreadsManagedExecutorService.java
Very often, the queue size is configured high, e.g. Integer.MAX_VALUE. So addition with maximal parallelization it overflows. This PR checks it and sets MAX_VALUE.
Plus a minor improvement in error log, displaying available number of threads to start (it should be zero if everything works well).
=> Fix Integer Overflow in Calculation of Virtual Thread Queue Size

osgi.bundle
Without this package, OSGi complains about missing package.
=> Add Virtual Threads Package to OSGi Exports

pom.xml
Specifically interceptor is updated to the final one, which now doesn't drag in the wrong annotations version anymore.
=> Update dependencies to the latest versions

src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedFutureTask.java
To avoid that the exception is swallowed in case there's no ManagedTask listener. 
Also add the original exception as the cause to add it to the stacktrace.
=> Throw exception in managed task so that it has to be handled or logged.

src/main/java/org/glassfish/concurro/internal/ManagedScheduledThreadPoolExecutor.java
Previous implementation used number of milliseconds for scheduling. The problem was during scheduling every second, sometimes the process was too fast, under 1 millisecond. The last time lost the nanoseconds part, e.g. `ZonedDateTime` planned the next execution to the exact same time. Keeping nanoseconds forces planning to the next second.
Example of executions with schedule `"* * * * * *"`:
```
Cron Trigger running, #4 at 19:30:22.302340267
Cron Trigger running, #5 at 19:30:23.000287937
Cron Trigger running, #6 at 19:30:23.303162670
Cron Trigger running, #7 at 19:30:24.000863731
```
The value `19:30:23.000287937` was converted to milliseconds, e.g. time `19:30:23` and the next schedule was `19:30:23` This is the behavior of [CronTrigger](https://github.com/jakartaee/concurrency/blob/dad8f …
=> Use Javatime in Managed Scheduled Thread Pool Executor

src/main/java/org/glassfish/concurro/cdi/ConcurrentCDIExtension.java
Fixes #88.
Deletes a SEVERE message in `ConcurrentCDIExtension#afterBeanDiscovery(AfterBeanDiscovery, BeanManager)` that was likely inserted for debugging purpose.
=> Delete redundant log message "afterBeanDiscovery" in ConcurrentCDIExtension

pom.xml
Avoid:
```
[INFO] --- surefire:3.2.5:test (default-test) @ concurro ---
[WARNING]  Parameter 'systemProperties' is deprecated: Use systemPropertyVariables instead.
```
=> Switch from deprecated `systemProperties` to `systemPropertyVariables`

src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedScheduledThreadPoolExecutor.java
This is a backport of 
* Issue: https://github.com/eclipse-ee4j/glassfish-concurro/issues/87
* Original master branch PR: https://github.com/eclipse-ee4j/glassfish-concurro/pull/68 (targeting 3.1.0)
The inner future (currentFuture) is used for repeating execution and its state is set to NORMAL/[Completed normally] after each cycle. The TriggerControllerFuture.cancel should return true even if this inner future is done.
=> Backport to 3.0.x: Succeed TriggerControllerFuture.cancel when inner future is done

src/main/java/org/glassfish/enterprise/concurrent/ManagedThreadFactoryImpl.java
=> Avoid NPE if task is set to null concurrently

src/main/java/org/glassfish/concurro/cdi/asynchronous/AsynchronousInterceptor.java
This is better than taking it off of the method instance, since using the context will also pick up synthetic annotations (those having been added by an extension)
=> Use invocation context to get interceptor binding

pom.xml, src/main/java/org/glassfish/concurro/virtualthreads/VirtualThreadsManagedExecutorService.java
Fixes https://github.com/eclipse-ee4j/glassfish-concurro/issues/121
Java 21 classes were built to the same location as Java 17 classes, and overwrote them.  The end result was that there are no multirelease classes and the virtual threads classes have Java 21 bytecode version, incompatible with Java 17 (as seen in the 3.1.0-M5 version)
I also set the tests to execute in parallel. A lot of them just schedule new threads and then wait for a couple of seconds, running them sequentially is just too slow for no purpose. It's safe to run them in parallel.
=> Fix multi-release build and speed up test execution and organize imports
