eclipse-ee4j/glassfish-concurro

- pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
> Update parent pom to EE4J superpom

- src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedScheduledThreadPoolExecutor.java
- src/test/java/org/glassfish/enterprise/concurrent/ManagedScheduledExecutorServiceAdapterTest.java
> Fixes #6 based on patch given in error report

- pom.xml
Requires API PR https://github.com/eclipse-ee4j/concurrency-api/pull/63
> Fixed api version number to that of Jakarta release

- pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
> Corrected version number to 1.1.1 for EE4J_8 branch

- pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
> Reverted API version to 1.1, changed name to jakarta

- pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
> Update parent pom to 1.0.4

- CONTRIBUTING.md
Signed-off-by: Mark Wareham <mark.wareham@payara.fish>
> Added contact info

- pom.xml
> Uptake Jakarta EE 8 released jars

- osgi.bundle
- pom.xml
> Fix the manifest to include correct OSGI metadata

- pom.xml
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
> Update api to RC2

- src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedFutureTask.java
Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>
> PAYARA-3122 Managed Scheduled Executor Service still executes tasks after undeployment

- .gitignore
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>
> Add most common rules to gitignore

- pom.xml
- src/main/java/org/glassfish/enterprise/concurrent/cdi/ConcurrentCDIExtension.java
- src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
> Backport Payara CDI Extension code to Concurrency Impl

- pom.xml
> Upgrade to latest service release of the api

- .gitignore
- pom.xml
- src/main/java/org/glassfish/enterprise/concurrent/ContextServiceImpl.java
Update versions in pom to Jakarta EE 11 M1
Update other versions in pom
Some cleaning
Add dash and consumer pom plug-ins
> Set version to 3.1.0-SNAPSHOT and update pom

- src/main/java/org/glassfish/enterprise/concurrent/AbstractPlatformThreadExecutorService.java
- src/main/java/org/glassfish/enterprise/concurrent/ForkJoinManagedExecutorService.java
- src/main/java/org/glassfish/enterprise/concurrent/ManagedExecutorServiceImpl.java
- src/main/java/org/glassfish/enterprise/concurrent/ManagedThreadFactoryImpl.java
- src/main/java21/org/glassfish/enterprise/concurrent/virtualthreads/VirtualThreadsManagedExecutorService.java
- src/test/java/org/glassfish/enterprise/concurrent/ManagedScheduledExecutorServiceImplTest.java
- src/test/java/org/glassfish/enterprise/concurrent/forkjoin/ForkJoinManagedExecutorServiceImplTest.java
- src/test/java/org/glassfish/enterprise/concurrent/test/ManagedTaskListenerImpl.java
- src/test/java/org/glassfish/enterprise/concurrent/test/TaskRunEnvironmentTracker.java
Add implementation of concurrency using JDK forkjoin pool instead of own thread pool.
> Add support for ForkJoin Pool

- src/main/java/org/glassfish/enterprise/concurrent/ManagedExecutorCompletionService.java
- src/main/java/org/glassfish/enterprise/concurrent/internal/ManagedFutureTask.java
- src/main/java/org/glassfish/enterprise/concurrent/internal/TaskDoneCallback.java
Mainly adding generic to TaskDoneCallback and update code using it. Some formatting there too.
> Small amount of code cleaning

- .github/workflows/concurro.yml
While waiting for
- #63
to be implemented I propose to have this GH Workflow.
> Setup GH Workflow

- osgi.bundle
- pom.xml
- src/main/java/org/glassfish/concurro/AsynchronousInterceptor.java
- src/main/java/org/glassfish/concurro/cdi/ConcurrencyManagedCDIBeans.java
- src/main/java/org/glassfish/concurro/cdi/ConcurrentCDIExtension.java
- src/main/java/org/glassfish/concurro/cdi/QualifierAnnotationProxy.java
- src/main/java/org/glassfish/concurro/internal/AsynchronousScheduledAction.java
- src/main/java/org/glassfish/concurro/internal/CompoundTrigger.java
- src/main/java/org/glassfish/concurro/internal/ConcurrencyManagedCDIBeans.java
Implementation of Concurrency 3.1 as much as it can be done by Concurro, currently works with the branch in Payara.
I'm going to help with the Glassfish part.
> Implement Concurrency 3.1

- src/main/java/org/glassfish/concurro/cdi/ConcurrencyManagedCDIBeans.java
- src/main/java/org/glassfish/concurro/cdi/ConcurrentCDIExtension.java
Just a typo, can wait for the next release.
Will require tiny change in Glassfish and Payara sources.
Thanks @kalinchan for spotting.
> Fix JNDI Name Typo

- pom.xml
- src/main/java/org/glassfish/concurro/virtualthreads/VirtualThreadsManagedExecutorService.java
- src/main/java/org/glassfish/concurro/virtualthreads/VirtualThreadsManagedFutureTask.java
- src/main/java/org/glassfish/concurro/virtualthreads/VirtualThreadsManagedScheduledExecutorService.java
- src/main/java/org/glassfish/concurro/virtualthreads/VirtualThreadsManagedThreadFactory.java
- src/test/java21/org/glassfish/concurro/test/virtualthreads/VirtualThreadsManagedExecutorServiceIT.java
- src/test/java21/org/glassfish/concurro/test/virtualthreads/VirtualThreadsManagedScheduledExecutorServiceIT.java
- src/test/java21/org/glassfish/concurro/test/virtualthreads/VirtualThreadsManagedThreadFactoryIT.java
Resolves https://github.com/eclipse-ee4j/glassfish-concurro/issues/104
> Add Dummy Virtual Thread Classes
